const imagePaths = {
  "02c": require("../assets/cards/deck/02c.png"),
  "02d": require("../assets/cards/deck/02d.png"),
  "02h": require("../assets/cards/deck/02h.png"),
  "02s": require("../assets/cards/deck/02s.png"),
  "03c": require("../assets/cards/deck/03c.png"),
  "03d": require("../assets/cards/deck/03d.png"),
  "03h": require("../assets/cards/deck/03h.png"),
  "03s": require("../assets/cards/deck/03s.png"),
  "04c": require("../assets/cards/deck/04c.png"),
  "04d": require("../assets/cards/deck/04d.png"),
  "04h": require("../assets/cards/deck/04h.png"),
  "04s": require("../assets/cards/deck/04s.png"),
  "05c": require("../assets/cards/deck/05c.png"),
  "05d": require("../assets/cards/deck/05d.png"),
  "05h": require("../assets/cards/deck/05h.png"),
  "05s": require("../assets/cards/deck/05s.png"),
  "06c": require("../assets/cards/deck/06c.png"),
  "06d": require("../assets/cards/deck/06d.png"),
  "06h": require("../assets/cards/deck/06h.png"),
  "06s": require("../assets/cards/deck/06s.png"),
  "07c": require("../assets/cards/deck/07c.png"),
  "07d": require("../assets/cards/deck/07d.png"),
  "07h": require("../assets/cards/deck/07h.png"),
  "07s": require("../assets/cards/deck/07s.png"),
  "08c": require("../assets/cards/deck/08c.png"),
  "08d": require("../assets/cards/deck/08d.png"),
  "08h": require("../assets/cards/deck/08h.png"),
  "08s": require("../assets/cards/deck/08s.png"),
  "09c": require("../assets/cards/deck/09c.png"),
  "09d": require("../assets/cards/deck/09d.png"),
  "09h": require("../assets/cards/deck/09h.png"),
  "09s": require("../assets/cards/deck/09s.png"),
  "10c": require("../assets/cards/deck/10c.png"),
  "10d": require("../assets/cards/deck/10d.png"),
  "10h": require("../assets/cards/deck/10h.png"),
  "10s": require("../assets/cards/deck/10s.png"),
  "11c": require("../assets/cards/deck/11c.png"),
  "11d": require("../assets/cards/deck/11d.png"),
  "11h": require("../assets/cards/deck/11h.png"),
  "11s": require("../assets/cards/deck/11s.png"),
  "12c": require("../assets/cards/deck/12c.png"),
  "12d": require("../assets/cards/deck/12d.png"),
  "12h": require("../assets/cards/deck/12h.png"),
  "12s": require("../assets/cards/deck/12s.png"),
  "13c": require("../assets/cards/deck/13c.png"),
  "13d": require("../assets/cards/deck/13d.png"),
  "13h": require("../assets/cards/deck/13h.png"),
  "13s": require("../assets/cards/deck/13s.png"),
  "14c": require("../assets/cards/deck/14c.png"),
  "14d": require("../assets/cards/deck/14d.png"),
  "14h": require("../assets/cards/deck/14h.png"),
  "14s": require("../assets/cards/deck/14s.png"),
};

export function getImagePaths(card) {
  return imagePaths[card];
}
